### ISSUE TITLE
function not found

### ISSUE THREAD

**Issue by mk-mohan** [deepanshu88/nser#1]
Thanks for this R code, I have been using it, but as of a week I have an error.

> out <- OptionChain('TATAPOWER', Expiry = 'latest')
Error in OptionChain("TATAPOWER", Expiry = "latest") : 
  could not find function "OptionChain"

I removed the package, and reinstalled it, > devtools::install_github("deepanshu88/nser")

but same error.

Thanks in advance

**Comment by deepanshu88** [comment]
Try this `nser::OptionChain('TATAPOWER', Expiry = 'latest')`

**Comment by mk-mohan** [comment]
Thanks for that. It worked when I tried this morning, honest to god the same thing did not two days ago.
My r environment seems to have become temperamental. 
Sorry to have waited you time.
